blank_issues_enabled: false
contact_links:
  - name: Conduit Backend Issue Tracker âš™ï¸
    url: https://github.com/ConduitPlatform/Conduit/issues
    about: Report issues related to the main Conduit repo
  - name: Admin Panel Issue Tracker ğŸ’»
    url: https://github.com/ConduitPlatform/Conduit-UI/issues
    about: Report issues related to the Conduit Admin Panel
  - name: Documentation ğŸ“„
    url: https://getconduit.dev/docs/overview/intro
    about: Check out our Documentation
  - name: Need Assistance? ğŸ†˜
    url: https://discord.gg/8xjzG75c
    about: Reach us on Discord
